import { Product } from './types/Product'

export const sampleProducts: Product[] = [
  {
    name: 'pinxer folha',
    slug: 'pinxer folha',
    category: 'preto',
    image: '../images/pincher-folha.png',
    price: 120,
    countInStock: 10,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 10,
    description: 'Na brisa leve de uma tarde serena, Um pincher folha dança em pleno voo.'
  },
  {
    name: 'pincher normal',
    slug: 'pincher normal',
    category: 'preto',
    image: '../images/pincher.jpg',
    price: 100,
    countInStock: 20,
    brand: 'Adidas',
    rating: 4.0,
    numReviews: 10,
    description: 'normal',
  },
  {
    name: 'pincher dançarino',
    slug: 'pincher dançarino',
    category: 'rajadopreto',
    image: '../images/pincher-dancarino.jpg',
    price: 220,
    countInStock: 0,
    brand: 'Lacoste',
    rating: 4.8,
    numReviews: 17,
    description: 'dancarino',
  },
  {
    name: 'pinxer rajado',
    slug: 'pinxer rajado',
    category: 'rajado',
    image: '../images/pinxer.jpg',
    price: 78,
    countInStock: 15,
    brand: 'Nike',
    rating: 4.5,
    numReviews: 14,
    description: 'rajado',
  },
]
